{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "8fc8f90b-c30d-49f5-9a53-3cb7b0bd7b34",
   "metadata": {},
   "source": [
    "##### The Aryn Partitioner is configured to use the Aryn Partitioning Service to provide fast, GPU-powered performance. Go to [aryn.ai/sign-up ](aryn.ai/sign-up) to get a free API key for the service. You can also run the Aryn Partitioner locally by changing `use_partitioning_service` to `False`. Though you can use CPU to run the Aryn Partitioner, it is recommended to use an NVIDIA GPU for good performance.\n",
    "\n",
    "\n",
    "##### In this example, we will write the output of the Sycamore from S3 to a target vector and keyword indexes in OpenSearch.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sycamore.data import Document\n",
    "from sycamore.functions import HuggingFaceTokenizer\n",
    "from sycamore.llms import OpenAI, OpenAIModels\n",
    "from sycamore.transforms.extract_schema import OpenAISchemaExtractor, OpenAIPropertyExtractor\n",
    "from sycamore.transforms.extract_entity import OpenAIEntityExtractor\n",
    "from sycamore.transforms.merge_elements import GreedyTextElementMerger\n",
    "from sycamore.transforms.partition import ArynPartitioner\n",
    "import sycamore"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "66cb1a15-5a04-44b9-96ca-9416c869528c",
   "metadata": {},
   "source": [
    "Replace the `aryn_api_key` with your key "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e6639325-d421-4d64-aa4e-a44c006df5c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "aryn_api_key = 'eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiZW1sIjoic29lYmhAYXJ5bi5haSIsImFjdCI6IjUxNDMyMDMyMTc3MiJ9LCJpYXQiOjE3MTk0Mjc1ODMuMDAxMDk0fQ.O_gBBkFfYftQxuyMxfYbAH15WW9tfhXPLJ9_jlFm68Pa5gS2gDNLtO2UpgV1pEUkNOshQcgZw0nlIcFUgOkHAQ'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1",
   "metadata": {},
   "outputs": [],
   "source": [
    "from dateutil import parser\n",
    "\n",
    "def convert_timestamp(doc: Document) -> Document:\n",
    "    if \"dateAndTime\" not in doc.properties['entity'] and \"dateTime\" not in doc.properties['entity']:\n",
    "        return doc\n",
    "    raw_date: str = doc.properties['entity'].get('dateAndTime') or doc.properties['entity'].get('dateTime')\n",
    "    raw_date = raw_date.replace(\"Local\", \"\")\n",
    "    parsed_date = parser.parse(raw_date, fuzzy=True)\n",
    "    extracted_date = parsed_date.date()\n",
    "    doc.properties['entity']['day'] = extracted_date.isoformat()\n",
    "    if parsed_date.utcoffset():\n",
    "        doc.properties['entity']['isoDateTime'] = parsed_date.isoformat()\n",
    "    else:\n",
    "        doc.properties['entity']['isoDateTime'] = parsed_date.isoformat() + \"Z\"\n",
    "    \n",
    "    return doc"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2",
   "metadata": {},
   "source": [
    "### Data loading"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "(MapWorker(ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)) pid=62972) The `max_size` parameter is deprecated and will be removed in v4.26. Please specify in `size['longest_edge'] instead`.\n"
     ]
    }
   ],
   "source": [
    "s3_path = \"s3://aryn-public/ntsb/\"\n",
    "llm = OpenAI(OpenAIModels.GPT_3_5_TURBO.value)\n",
    "tokenizer = HuggingFaceTokenizer(\"thenlper/gte-small\")\n",
    "\n",
    "ctx = sycamore.init()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4",
   "metadata": {},
   "outputs": [],
   "source": [
    "docset = (\n",
    "    ctx.read.binary(s3_path, parallelism=4, binary_format=\"pdf\")\n",
    "    .partition(partitioner=ArynPartitioner(aryn_api_key=aryn_api_key, aryn_partitioner_address=\"https://api.aryn.cloud/v1/document/partition\"))\n",
    "    )"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5",
   "metadata": {},
   "source": [
    "### Data extraction"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "6",
   "metadata": {},
   "outputs": [],
   "source": [
    "docset = (\n",
    "    docset\n",
    "    .extract_batch_schema(schema_extractor=OpenAISchemaExtractor(\"FlightAccidentReport\", llm=llm, num_of_elements=35))\n",
    "    .extract_properties(property_extractor=OpenAIPropertyExtractor(llm=llm, num_of_elements=35))\n",
    "    .merge(GreedyTextElementMerger(tokenizer, 300))\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7",
   "metadata": {},
   "outputs": [],
   "source": [
    "docset = docset.map(convert_timestamp)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "8",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-07-09 09:57:17,170\tWARNING read_api.py:2977 -- The argument ``parallelism`` is deprecated in Ray 2.10. Please specify argument ``override_num_blocks`` instead.\n",
      "2024-07-09 09:57:17,912\tWARNING util.py:560 -- The argument ``compute`` is deprecated in Ray 2.9. Please specify argument ``concurrency`` instead. For more information, see https://docs.ray.io/en/master/data/transforming-data.html#stateful-transforms.\n",
      "2024-07-09 09:57:17,915\tINFO streaming_executor.py:112 -- Starting execution of Dataset. Full logs are in /tmp/ray/session_2024-07-09_09-57-07_819296_62943/logs/ray-data\n",
      "2024-07-09 09:57:17,916\tINFO streaming_executor.py:113 -- Execution plan of Dataset: InputDataBuffer[Input] -> ActorPoolMapOperator[ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)] -> TaskPoolMapOperator[MapBatches(extract_properties)->MapBatches(merge_elements)->MapBatches(convert_timestamp)]\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "- ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract) 1: …"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "- MapBatches(extract_properties)->MapBatches(merge_elements)->MapBatches(convert_timestamp) 2:   0%|          …"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Running 0:   0%|                                                                                              …"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-07-09 10:08:07,045\tERROR streaming_executor_state.py:449 -- An exception was raised from a task of operator \"ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)\". Dataset execution will now abort. To ignore this exception and continue, set DataContext.max_errored_blocks.\n",
      "2024-07-09 10:08:07,059\tWARNING actor_pool_map_operator.py:292 -- To ensure full parallelization across an actor pool of size 1, the Dataset should consist of at least 1 distinct blocks. Consider increasing the parallelism when creating the Dataset.\n",
      "2024-07-09 10:08:07,062\tERROR exceptions.py:63 -- Exception occurred in user code, with the abbreviated stack trace below. By default, the Ray Data internal stack trace is omitted from stdout, and only written to the Ray Data log files at /tmp/ray/session_2024-07-09_09-57-07_819296_62943/logs/ray-data. To output the full stack trace to stdout, set `DataContext.log_internal_stack_trace_to_stdout` to True.\n"
     ]
    },
    {
     "ename": "RayTaskError(UserCodeException)",
     "evalue": "\u001b[36mray::ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)()\u001b[39m (pid=62972, ip=127.0.0.1, actor_id=448723e021ce19d2d819c51801000000, repr=MapWorker(ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)))\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/detr_partitioner.py\", line 209, in _partition_remote\n    raise ArynPDFPartitionerException(\nsycamore.transforms.detr_partitioner.ArynPDFPartitionerException: Error: status_code: 500, reason: Internal Server Error\n\nThe above exception was the direct cause of the following exception:\n\n\u001b[36mray::ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)()\u001b[39m (pid=62972, ip=127.0.0.1, actor_id=448723e021ce19d2d819c51801000000, repr=MapWorker(ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)))\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/partition.py\", line 483, in partition\n    elements = partitioner.partition_pdf(\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/detr_partitioner.py\", line 131, in partition_pdf\n    return self._partition_remote(\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/tenacity/__init__.py\", line 332, in wrapped_f\n    return self(f, *args, **kw)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/tenacity/__init__.py\", line 469, in __call__\n    do = self.iter(retry_state=retry_state)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/tenacity/__init__.py\", line 370, in iter\n    result = action(retry_state)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/tenacity/__init__.py\", line 413, in exc_check\n    raise retry_exc from fut.exception()\ntenacity.RetryError: RetryError[<Future at 0x16c1409a0 state=finished raised ArynPDFPartitionerException>]\n\nThe above exception was the direct cause of the following exception:\n\n\u001b[36mray::ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)()\u001b[39m (pid=62972, ip=127.0.0.1, actor_id=448723e021ce19d2d819c51801000000, repr=MapWorker(ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)))\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py\", line 125, in fn\n    return op_fn(item, *fn_args, **fn_kwargs)\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/base.py\", line 178, in ray_callable\n    return BaseMapTransform._process_ray(ray_input, name, lambda d: f(d, *args, **kwargs), enable_auto_metadata)\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/base.py\", line 230, in _process_ray\n    outputs = f(docs)\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/base.py\", line 178, in <lambda>\n    return BaseMapTransform._process_ray(ray_input, name, lambda d: f(d, *args, **kwargs), enable_auto_metadata)\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/map.py\", line 49, in _wrap\n    return [f(d, *args, **kwargs) for d in docs]\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/map.py\", line 49, in <listcomp>\n    return [f(d, *args, **kwargs) for d in docs]\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/utils/time_trace.py\", line 136, in wrapper\n    return f(*args, **kwargs)\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/partition.py\", line 501, in partition\n    raise RuntimeError(f\"SycamorePartitioner Error processing {path}\") from e\nRuntimeError: SycamorePartitioner Error processing s3://aryn-public/ntsb/0.pdf\n\nThe above exception was the direct cause of the following exception:\n\n\u001b[36mray::ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)()\u001b[39m (pid=62972, ip=127.0.0.1, actor_id=448723e021ce19d2d819c51801000000, repr=MapWorker(ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)))\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/actor_pool_map_operator.py\", line 403, in submit\n    yield from _map_task(\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py\", line 419, in _map_task\n    for b_out in map_transformer.apply_transform(iter(blocks), ctx):\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py\", line 155, in apply_transform\n    iter = transform_fn(iter, ctx)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py\", line 309, in __call__\n    first = next(block_iter, None)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py\", line 392, in __call__\n    for data in iter:\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py\", line 134, in _udf_timed_iter\n    output = next(input)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py\", line 236, in __call__\n    yield from self._batch_fn(input, ctx)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py\", line 208, in transform_fn\n    res = fn(batch)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py\", line 127, in fn\n    _handle_debugger_exception(e)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py\", line 143, in _handle_debugger_exception\n    raise UserCodeException() from e\nray.exceptions.UserCodeException",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRayTaskError(UserCodeException)\u001b[0m           Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[8], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m sample_docs \u001b[38;5;241m=\u001b[39m \u001b[43mdocset\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtake\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/docset.py:169\u001b[0m, in \u001b[0;36mDocSet.take\u001b[0;34m(self, limit, include_metadata)\u001b[0m\n\u001b[1;32m    167\u001b[0m dataset \u001b[38;5;241m=\u001b[39m execution\u001b[38;5;241m.\u001b[39mexecute(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mplan)\n\u001b[1;32m    168\u001b[0m ret \u001b[38;5;241m=\u001b[39m []\n\u001b[0;32m--> 169\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m row \u001b[38;5;129;01min\u001b[39;00m dataset\u001b[38;5;241m.\u001b[39miter_rows():\n\u001b[1;32m    170\u001b[0m     doc \u001b[38;5;241m=\u001b[39m Document\u001b[38;5;241m.\u001b[39mfrom_row(row)\n\u001b[1;32m    171\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m include_metadata \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(doc, MetadataDocument):\n",
      "File \u001b[0;32m~/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/iterator.py:245\u001b[0m, in \u001b[0;36mDataIterator.iter_rows.<locals>._wrapped_iterator\u001b[0;34m()\u001b[0m\n\u001b[1;32m    244\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_wrapped_iterator\u001b[39m():\n\u001b[0;32m--> 245\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m batch \u001b[38;5;129;01min\u001b[39;00m batch_iterable:\n\u001b[1;32m    246\u001b[0m         batch \u001b[38;5;241m=\u001b[39m BlockAccessor\u001b[38;5;241m.\u001b[39mfor_block(BlockAccessor\u001b[38;5;241m.\u001b[39mbatch_to_block(batch))\n\u001b[1;32m    247\u001b[0m         \u001b[38;5;28;01mfor\u001b[39;00m row \u001b[38;5;129;01min\u001b[39;00m batch\u001b[38;5;241m.\u001b[39miter_rows(public_row_format\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m):\n",
      "File \u001b[0;32m~/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/iterator.py:162\u001b[0m, in \u001b[0;36mDataIterator.iter_batches.<locals>._create_iterator\u001b[0;34m()\u001b[0m\n\u001b[1;32m    157\u001b[0m time_start \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mperf_counter()\n\u001b[1;32m    158\u001b[0m \u001b[38;5;66;03m# Iterate through the dataset from the start each time\u001b[39;00m\n\u001b[1;32m    159\u001b[0m \u001b[38;5;66;03m# _iterator_gen is called.\u001b[39;00m\n\u001b[1;32m    160\u001b[0m \u001b[38;5;66;03m# This allows multiple iterations of the dataset without\u001b[39;00m\n\u001b[1;32m    161\u001b[0m \u001b[38;5;66;03m# needing to explicitly call `iter_batches()` multiple times.\u001b[39;00m\n\u001b[0;32m--> 162\u001b[0m block_iterator, stats, blocks_owned_by_consumer \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_to_block_iterator\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    164\u001b[0m iterator \u001b[38;5;241m=\u001b[39m \u001b[38;5;28miter\u001b[39m(\n\u001b[1;32m    165\u001b[0m     iter_batches(\n\u001b[1;32m    166\u001b[0m         block_iterator,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    177\u001b[0m     )\n\u001b[1;32m    178\u001b[0m )\n\u001b[1;32m    180\u001b[0m dataset_tag \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_get_dataset_tag()\n",
      "File \u001b[0;32m~/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/iterator/iterator_impl.py:33\u001b[0m, in \u001b[0;36mDataIteratorImpl._to_block_iterator\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     25\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_to_block_iterator\u001b[39m(\n\u001b[1;32m     26\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m     27\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Tuple[\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     30\u001b[0m     \u001b[38;5;28mbool\u001b[39m,\n\u001b[1;32m     31\u001b[0m ]:\n\u001b[1;32m     32\u001b[0m     ds \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_base_dataset\n\u001b[0;32m---> 33\u001b[0m     block_iterator, stats, executor \u001b[38;5;241m=\u001b[39m \u001b[43mds\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_plan\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexecute_to_iterator\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     34\u001b[0m     ds\u001b[38;5;241m.\u001b[39m_current_executor \u001b[38;5;241m=\u001b[39m executor\n\u001b[1;32m     35\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m block_iterator, stats, \u001b[38;5;28;01mFalse\u001b[39;00m\n",
      "File \u001b[0;32m~/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/exceptions.py:84\u001b[0m, in \u001b[0;36momit_traceback_stdout.<locals>.handle_trace\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     80\u001b[0m logger\u001b[38;5;241m.\u001b[39mexception(\n\u001b[1;32m     81\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mFull stack trace:\u001b[39m\u001b[38;5;124m\"\u001b[39m, exc_info\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m, extra\u001b[38;5;241m=\u001b[39m{\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhide\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;129;01mnot\u001b[39;00m log_to_stdout}\n\u001b[1;32m     82\u001b[0m )\n\u001b[1;32m     83\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m is_user_code_exception:\n\u001b[0;32m---> 84\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[1;32m     85\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     86\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(\u001b[38;5;28;01mNone\u001b[39;00m) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mSystemException\u001b[39;00m()\n",
      "\u001b[0;31mRayTaskError(UserCodeException)\u001b[0m: \u001b[36mray::ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)()\u001b[39m (pid=62972, ip=127.0.0.1, actor_id=448723e021ce19d2d819c51801000000, repr=MapWorker(ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)))\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/detr_partitioner.py\", line 209, in _partition_remote\n    raise ArynPDFPartitionerException(\nsycamore.transforms.detr_partitioner.ArynPDFPartitionerException: Error: status_code: 500, reason: Internal Server Error\n\nThe above exception was the direct cause of the following exception:\n\n\u001b[36mray::ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)()\u001b[39m (pid=62972, ip=127.0.0.1, actor_id=448723e021ce19d2d819c51801000000, repr=MapWorker(ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)))\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/partition.py\", line 483, in partition\n    elements = partitioner.partition_pdf(\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/detr_partitioner.py\", line 131, in partition_pdf\n    return self._partition_remote(\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/tenacity/__init__.py\", line 332, in wrapped_f\n    return self(f, *args, **kw)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/tenacity/__init__.py\", line 469, in __call__\n    do = self.iter(retry_state=retry_state)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/tenacity/__init__.py\", line 370, in iter\n    result = action(retry_state)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/tenacity/__init__.py\", line 413, in exc_check\n    raise retry_exc from fut.exception()\ntenacity.RetryError: RetryError[<Future at 0x16c1409a0 state=finished raised ArynPDFPartitionerException>]\n\nThe above exception was the direct cause of the following exception:\n\n\u001b[36mray::ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)()\u001b[39m (pid=62972, ip=127.0.0.1, actor_id=448723e021ce19d2d819c51801000000, repr=MapWorker(ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)))\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py\", line 125, in fn\n    return op_fn(item, *fn_args, **fn_kwargs)\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/base.py\", line 178, in ray_callable\n    return BaseMapTransform._process_ray(ray_input, name, lambda d: f(d, *args, **kwargs), enable_auto_metadata)\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/base.py\", line 230, in _process_ray\n    outputs = f(docs)\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/base.py\", line 178, in <lambda>\n    return BaseMapTransform._process_ray(ray_input, name, lambda d: f(d, *args, **kwargs), enable_auto_metadata)\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/map.py\", line 49, in _wrap\n    return [f(d, *args, **kwargs) for d in docs]\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/map.py\", line 49, in <listcomp>\n    return [f(d, *args, **kwargs) for d in docs]\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/utils/time_trace.py\", line 136, in wrapper\n    return f(*args, **kwargs)\n  File \"/Users/sheb/Desktop/GITHUB/notebookchanges/sycamore/lib/sycamore/sycamore/transforms/partition.py\", line 501, in partition\n    raise RuntimeError(f\"SycamorePartitioner Error processing {path}\") from e\nRuntimeError: SycamorePartitioner Error processing s3://aryn-public/ntsb/0.pdf\n\nThe above exception was the direct cause of the following exception:\n\n\u001b[36mray::ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)()\u001b[39m (pid=62972, ip=127.0.0.1, actor_id=448723e021ce19d2d819c51801000000, repr=MapWorker(ReadBinary->Map(BinaryScan._to_document)->MapBatches(_wrap)->MapBatches(BaseMapTransformCustom__Extract)))\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/actor_pool_map_operator.py\", line 403, in submit\n    yield from _map_task(\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_operator.py\", line 419, in _map_task\n    for b_out in map_transformer.apply_transform(iter(blocks), ctx):\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py\", line 155, in apply_transform\n    iter = transform_fn(iter, ctx)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py\", line 309, in __call__\n    first = next(block_iter, None)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py\", line 392, in __call__\n    for data in iter:\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py\", line 134, in _udf_timed_iter\n    output = next(input)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/execution/operators/map_transformer.py\", line 236, in __call__\n    yield from self._batch_fn(input, ctx)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py\", line 208, in transform_fn\n    res = fn(batch)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py\", line 127, in fn\n    _handle_debugger_exception(e)\n  File \"/Users/sheb/Library/Caches/pypoetry/virtualenvs/sycamore-monorepo--rUP0lTI-py3.9/lib/python3.9/site-packages/ray/data/_internal/planner/plan_udf_map_op.py\", line 143, in _handle_debugger_exception\n    raise UserCodeException() from e\nray.exceptions.UserCodeException"
     ]
    }
   ],
   "source": [
    "sample_docs = docset.take()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9",
   "metadata": {},
   "outputs": [],
   "source": [
    "sample_docs[0].properties['_schema']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "10",
   "metadata": {},
   "outputs": [],
   "source": [
    "sample_docs[0].properties['entity']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "11",
   "metadata": {},
   "outputs": [],
   "source": [
    "for d in sample_docs:\n",
    "    print(f\"Path: {d.properties['path']}\")\n",
    "    for k in [\"dateAndTime\", \"day\", \"aircraft\", \"location\"]:\n",
    "            print(f\"{k: <25} {d.properties['entity'].get(k, 'None')}\")\n",
    "    print()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "12",
   "metadata": {},
   "source": [
    "## Indexing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "13",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sycamore.transforms.embed import SentenceTransformerEmbedder\n",
    "import os\n",
    "\n",
    "if os.path.exists(\"/.dockerenv\"):\n",
    "    opensearch_host = \"opensearch\"\n",
    "    print(\"Assuming we are in a Sycamore Jupyter container, using opensearch for OpenSearch host\")\n",
    "else:\n",
    "    opensearch_host = \"localhost\"\n",
    "    print(\"Assuming we are running outside of a container, using localhost for OpenSearch host\")\n",
    "\n",
    "index = \"ntsb_Aryn\"\n",
    "os_client_args = {\n",
    "    \"hosts\": [{\"host\": opensearch_host, \"port\": 9200}],\n",
    "    \"http_compress\": True,\n",
    "    \"http_auth\": (\"admin\", \"admin\"),\n",
    "    \"use_ssl\": True,\n",
    "    \"verify_certs\": False,\n",
    "    \"ssl_assert_hostname\": False,\n",
    "    \"ssl_show_warn\": False,\n",
    "    \"timeout\": 120,\n",
    "}\n",
    "\n",
    "index_settings = {\n",
    "    \"body\": {\n",
    "        \"settings\": {\n",
    "            \"index.knn\": True,\n",
    "            \"number_of_shards\": 5,\n",
    "            \"number_of_replicas\": 1\n",
    "        },\n",
    "        \"mappings\": {\n",
    "            \"properties\": {\n",
    "                \"embedding\": {\n",
    "                  \"dimension\": 384,\n",
    "                  \"method\": {\n",
    "                    \"engine\": \"faiss\",\n",
    "                    \"space_type\": \"l2\",\n",
    "                    \"name\": \"hnsw\",\n",
    "                    \"parameters\": {}\n",
    "                  },\n",
    "                  \"type\": \"knn_vector\"\n",
    "                }\n",
    "            }\n",
    "        }\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "14",
   "metadata": {},
   "outputs": [],
   "source": [
    "docset = (\n",
    "    docset\n",
    "    .spread_properties([\"entity\", \"path\"])\n",
    "    .explode()\n",
    "    .sketch()\n",
    "    .embed(embedder=SentenceTransformerEmbedder(batch_size=100, model_name=\"sentence-transformers/all-MiniLM-L6-v2\"))\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15",
   "metadata": {},
   "outputs": [],
   "source": [
    "docset.write.opensearch(\n",
    "    os_client_args=os_client_args,\n",
    "    index_name=index,\n",
    "    index_settings=index_settings,\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "814c828d-2bd1-4326-b39c-190d03d63622",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
